test

diff --git a/.github/workflows/update-version.yml b/.github/workflows/update-version.yml
--- a/.github/workflows/update-version.yml
+++ b/.github/workflows/update-version.yml
@@ -58,14 +58,15 @@ jobs:
           minor=$(echo "$current_version" | cut -d. -f2)
           patch=$(echo "$current_version" | cut -d. -f3)
 
-          if [[ -z "$major" || -z "$minor" || -z "$patch" ]]; then
-            echo "Version parsing failed: $current_version"
-            exit 1
-          fi
+          # if [[ -z "$major" || -z "$minor" || -z "$patch" ]]; then
+          #   echo "Version parsing failed: $current_version"
+          #   exit 1
+          # fi
 
           case "$BUMP" in
             patch) 
               ((patch++)) 
+              echo "DAAAAA"
               ;;
             minor) 
               ((minor++))
