test

diff --git a/.github/workflows/update-version.yml b/.github/workflows/update-version.yml
--- a/.github/workflows/update-version.yml
+++ b/.github/workflows/update-version.yml
@@ -49,44 +49,36 @@ jobs:
           current_version="${{ env.version }}"
           current_version="${current_version#v}"  
 
-          echo "Current version: $current_version"
           if [[ ! $current_version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
             echo "Version format is invalid: $current_version"
             exit 1
           fi
-          echo "NU"
+
           major=$(echo "$current_version" | cut -d. -f1)
           minor=$(echo "$current_version" | cut -d. -f2)
           patch=$(echo "$current_version" | cut -d. -f3)
 
-          # if [[ -z "$major" || -z "$minor" || -z "$patch" ]]; then
-          #   echo "Version parsing failed: $current_version"
-          #   exit 1
-          # fi
-          echo "BUMP = $BUMP"
+          if [[ -z "$major" || -z "$minor" || -z "$patch" ]]; then
+            echo "Version parsing failed: $current_version"
+            exit 1
+          fi
+
           case "$BUMP" in
             patch) 
-              ((patch++)) 
-
+              patch=$((patch + 1))
               ;;
             minor) 
-              echo "minor $minor"
               minor=$((minor + 1))
-              echo "minor $minor"
-              patch=0  # Resetăm patch-ul
+              patch=0
               ;;
             major) 
-              ((major++))
+              minor=$((major + 1))
               minor=0   # Resetăm minor
               patch=0   # Resetăm patch
               ;;
           esac
 
-          echo "major: $major"
-          echo "minor: $minor"
-          echo "patch: $patch"
-
-          new_version="v${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
+          new_version="v${major}.${minor}.${patch}"
           echo "New version: $new_version"
           echo "new_version=$new_version" >> $GITHUB_ENV
 
